<a href="https://colab.research.google.com/github/nxfive/DataScience/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

np.__version__

'1.21.6'

In [ ]:
dir(np)

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [5]:
# 1D Array
x = np.array([1, 3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim  #wymiar tablicy

1

In [9]:
x.shape  #kształt tablicy

(2,)

In [11]:
x.size   #liczba elementow w tablicy

2

In [12]:
x.dtype  #typ naszych danych w tablicy

dtype('int64')

In [14]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [15]:
x.dtype

dtype('float64')

In [19]:
# 2D array

x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [20]:
x.ndim 

2

In [21]:
x.shape

(2, 2)

In [22]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [23]:
x.shape

(2, 3)

In [28]:
# 3D array

x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [29]:
x.ndim

3

In [30]:
x.shape   # 3 elementy po 2 wiersze po 3 kolumny

(3, 2, 3)

Typy danych

In [31]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [32]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [33]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [34]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [35]:
A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

dtype('int64')

In [36]:
A

array([1, 2, 3])

In [37]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [38]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)  #0 - 255
A.dtype

Tworzenie tablic

In [39]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [41]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.ones(shape=(5, 5), dtype='int')


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [47]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [49]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [50]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [51]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
# zmiana rozmiaru danych
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
A.reshape((3, -1)) # kiedy chcemy miec 3 wiersze a kolumny maja sie dobrac automatycznie

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Podstawowe operacje na tablicach

In [57]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [58]:
# przy dodawaniu rozmiar tablic powinien byc taki sam

A + B

array([6, 0, 7, 4])

In [59]:
A - B

array([0, 2, 1, 0])

In [60]:
A * B

array([ 9, -1, 12,  4])

In [61]:
# przy dzieleniu tablica przez ktora dzielimy nie moze zawierac 0
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.add(A, B)

In [65]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [66]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [67]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [62]:
A + 3   # doda 3 do kazdego elementu

array([6, 4, 7, 5])

In [63]:
2 * A

array([6, 2, 8, 4])

In [64]:
A + 3 * B

array([12, -2, 13,  8])

In [69]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [70]:
np.dot(X, Y)  #mnozenie maciezowe

array([[  3,   6],
       [-12,   0]])

In [71]:
#mnozenie maciezy nie jest przemienne
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [72]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [73]:
X @ Y    #mnozenie maciezowe

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [75]:
np.random.seed(0)

In [76]:
np.random.randn()  #losowa wartosc z rozkladu normalnego

1.764052345967664

In [78]:
np.random.randn(10)  #10 liczb z rozkladu normalnego o sredniej 0 i odchyleniu standardowym 1

array([ 1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433,
        1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982])

In [79]:
np. random.randn(10, 4)

array([[ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297],
       [-1.42001794, -1.70627019,  1.9507754 , -0.50965218],
       [-0.4380743 , -1.25279536,  0.77749036, -1.61389785],
       [-0.21274028, -0.89546656,  0.3869025 , -0.51080514],
       [-1.18063218, -0.02818223,  0.42833187,  0.06651722],
       [ 0.3024719 , -0.63432209, -0.36274117, -0.67246045]])

In [80]:
# rozklad jednostajny na przedziale
np.random.rand()  # zwroci wartosc losowa z przedzialu 0-1

0.317983179393976

In [81]:
np.random.rand(10)

array([0.41426299, 0.0641475 , 0.69247212, 0.56660145, 0.26538949,
       0.52324805, 0.09394051, 0.5759465 , 0.9292962 , 0.31856895])

In [82]:
np.random.rand(10, 2)

array([[0.66741038, 0.13179786],
       [0.7163272 , 0.28940609],
       [0.18319136, 0.58651293],
       [0.02010755, 0.82894003],
       [0.00469548, 0.67781654],
       [0.27000797, 0.73519402],
       [0.96218855, 0.24875314],
       [0.57615733, 0.59204193],
       [0.57225191, 0.22308163],
       [0.95274901, 0.44712538]])

In [83]:
np.random.randint(10)  # zwroci losowo z przedzialu 0-10 bez ost.

4

In [84]:
np.random.randint(low=10, high=101)

77

In [85]:
np.random.randint(low=10, high=101, size=10)

array([21, 96, 87, 85, 66, 26, 34, 39, 31, 35])

In [88]:
np.random.choice([4, 2, 1, 3])  #losowy element z listy

2

In [89]:
np.random.choice(['python', 'java', 'sql'])

'sql'

In [90]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
#przetasowanie danych
np.random.shuffle(data)

In [92]:
data

array([2, 9, 7, 8, 4, 6, 0, 1, 3, 5])

Podstawowe funkcje

In [93]:
np.exp(1)  #stała Eulera

2.718281828459045

In [94]:
np.sqrt(9)

3.0

In [95]:
np.all([2, 3, 1])   # jesli kazda wartosc zwroci prawde to zwroci True

True

In [96]:
np.any([1, 2, 1])   #sprawdza czy jakikolwiek obiekt jest prawda

True

In [97]:
np.any([0, 0, 0])

False

In [98]:
A = np.random.rand(5)
A

array([0.30157482, 0.66017354, 0.29007761, 0.61801543, 0.4287687 ])

In [99]:
np.argmax(A)  #zwroci indeks wartosci najwiekszej

1

In [100]:
# najwieksza wartosc z tablicy
A[np.argmax(A)]

0.660173537492685

In [101]:
np.argmin(A)  #zwroci indeks wartosci najmniejszej

2

In [103]:
np.argsort(A)  # sortowanie ze zwracaniem indeksow wartosci

array([2, 0, 4, 3, 1])

In [104]:
np.max(A)

0.660173537492685

In [105]:
np.min(A)

0.29007760721044407

In [106]:
np.mean(A)  #srednia

0.45972201826445724

In [107]:
np.median(A) #wartosc srodkowa z posortowanego zbioru lub srednia 2 srodkowych wartosci

0.42876870094576613

In [108]:
np.std(A)  # odchylenie standardowe informuje o tym, jak szeroko wartości danej wielkości są rozrzucone wokół jej średniej

0.1549099653788888

Indeksowanie, wycinanie

In [109]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [110]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [111]:
A[2]

2

In [112]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [113]:
A[:2]

array([0, 1])

In [114]:
A[-1]

19

In [115]:
A[10:15]

array([10, 11, 12, 13, 14])

In [116]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [117]:
# wycinanie wierszy 
A[0]

array([0, 1, 2, 3, 4])

In [118]:
# wycinanie pierwszej kolumny
A[:, 0]

array([ 0,  5, 10, 15])

In [119]:
# wycinanie ostatniej kolumny
A[:, -1]

array([ 4,  9, 14, 19])

In [120]:
A[:, -2]

array([ 3,  8, 13, 18])

In [121]:
# wycinanie elementu 6
A[1][1]

6

In [122]:
A[1:2, 1:4]

array([[6, 7, 8]])

In [123]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [126]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [127]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [128]:
for row in A:
    print(row[0])

0
5
10
15


In [129]:
for row in A:
    print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [130]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [131]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [132]:
A.shape

(4, 5)

In [133]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [134]:
A.ravel() #powrot do plaskiej postaci

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [135]:
# transponowana macierz (tablica) zamienia kolumny na wiersze

A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [136]:
A = np.arange(start=-10, stop=10, step=0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [137]:
A = A.reshape(10, -1)

In [138]:
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [139]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [140]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [141]:
np.bitwise_and(A > -5, A < 5) # true kiedy oba warunki sa spelnione

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [142]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])